AdminPanelMVC/Controllers/ColorController.cs
using Business.Abstract;
using Entities.Concrete;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AdminPanelMVC.Controllers
{
    public class ColorController : Controller
    {
        private IColorService _colorService;
        public ColorController(IColorService colorService)
        {
            _colorService = colorService;
        }
        public IActionResult Index()
        {
            var colors = _colorService.GetAll().Data;
            return View(colors);
        }
        [HttpGet]
        public ActionResult AddColor()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddColor(Color color)
        {
            _colorService.Add(color);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult EditColor(int id)
        {
            var colorToUpdate = _colorService.GetColorById(id).Data;
            return View(colorToUpdate);
        }
        [HttpPost]
        public ActionResult EditColor(Color color)
        {
            _colorService.Update(color);
            return RedirectToAction("Index");
        }
        public ActionResult DeleteColor(int id)
        {
            var colorToDelete = _colorService.GetColorById(id).Data;
            _colorService.Delete(colorToDelete);
            return RedirectToAction("Index");

        }
    }
}

AdminPanelMVC/Views/Color/AddColor.cshtml
@model Entities.Concrete.Color
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h1>Renk Ekle</h1>
<br />
@using (Html.BeginForm("AddColor", "Color", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Renk Adı")
        @Html.TextBoxFor(x => x.ColorName, new { @class = "form-control" })
        <br />
        <button class="btn btn-success">Kaydet</button>
    </div>
}

AdminPanelMVC/Views/Color/EditColor.cshtml
@model Entities.Concrete.Color
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Marka Güncelle</h2>
@using (Html.BeginForm("EditColor", "Color", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.ColorId, new { @class = "form-control" })
        @Html.Label("Renk Adı")
        @Html.TextBoxFor(x => x.ColorName, new { @class = "form-control" })
        <br />
        <button class="btn btn-success">Güncelle</button>
    </div>
}

AdminPanelMVC/Views/Color/Index.cshtml
@using Entities.Concrete
@model List<Color>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <!-- Content Header (Page header) -->
    <!-- Main content -->
    <section class="content pt-3">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <a href="/Color/AddColor/" class="btn btn-success"><i class="fas fa-plus"></i></a>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 20%">
                                Renk Adı
                            </th>
                            <th style="width: 15%;float:right">
                                İşlemler
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {

                            <tr>
                                <td>
                                    @item.ColorId
                                </td>
                                <td>
                                    <a>
                                        @item.ColorName
                                    </a>
                                </td>
                                <td class="project-actions text-right">
                                    <a class="btn btn-info btn-sm" href="/Color/EditColor/@item.ColorId">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Düzenle
                                    </a>
                                    <a class="btn btn-danger btn-sm" href="/Color/DeleteColor/@item.ColorId">
                                        <i class="fas fa-trash">
                                        </i>
                                        Sil
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->

    </section>

    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="../../plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="../../dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="../../dist/js/demo.js"></script>
</body>
</html>